import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Link from 'next/link';
import { ChartColumnBigIcon } from 'lucide-react';
import { ClerkProvider, Show, SignInButton, SignUpButton } from '@clerk/nextjs';
import { Button } from '@/components/ui/button';
import UserDropdown from './user-dropdown';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('h-full', 'antialiased', inter.variable)}>
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href="/"
              className="font-bold text-2xl flex gap-1 items-center"
            >
              <ChartColumnBigIcon className="text-lime-500" /> Glitchless Cash
              Flow
            </Link>
            <div>
              <Show when="signed-out">
                <div className="flex items-center">
                  <Button asChild variant="link" className="text-white">
                    <SignInButton />
                  </Button>
                  <Button asChild variant="link" className="text-white">
                    <SignUpButton />
                  </Button>
                </div>
              </Show>
              <Show when="signed-in">
                <UserDropdown />
              </Show>
            </div>
          </nav>
          {children}
          <Toaster />
        </ClerkProvider>
      </body>
    </html>
  );
}
